name = "Astral Create + 航空学"
author = "Astral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19e75a953b1b50e2a1fa7c7557b6ee997e96e330250975821ed5a32631274eb9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
